home/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

#from .views import HomePage
from . import views

app_name = "home"

urlpatterns = [

    path('', views.HomePage, name="home"),
    #path('products', views.ProductsPage, name="products"),
    path('products_checkout', views.ProductsCheckout, name="products_checkout"),
    path('products_transaction/<subscription_id>', views.ProductsTransaction, name="products_transaction"),
    path('about', views.AboutUsPage, name="about"),
    path('profile', views.ProfilePage, name="profile"),
    path('profile/update', views.ProfileUpdate, name="profile_update"),
    path('profile/migrate_sub', views.ProfileMigrateSub, name="profile_migrate_sub"),
    path('profile/cancel_sub', views.ProfileCancelSub, name="profile_cancel_sub"),
    
    path('profile/discord_auth', views.DiscordAuth, name="discord_auth"),
    path('profile/tv_auth', views.TvAuth, name="tv_auth"),
    path('profile/mt5_license', views.MT5Licence, name="mt5_license"),
    path('profile/discord_authc', views.DiscordAuthC, name="discord_authc"),
    path('profile/get_ctable', views.AdCustomerTable, name="profile_ad_ctable"),
    path('algo_getting_started', views.AlgoGSPage, name="algo_gs"),
    path('algo_mmsigma', views.AlgoMMSIGMAPage, name="algo_mmsigma"),
    
    path('auth_f/', include('auth_f.urls')),
    
    

] 

mmi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('auth_f/', include('auth_f.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
import django
from django.db import models

# Create your models here.

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

from datetime import date, datetime
import time

from django.utils import timezone

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
    ("Free", "Free"),
    ("MM Bundle Monthly","MMB1M"),
    ("MM Bundle Quarterly","MMB3M"),
    ("MM Bundle Semestral","MMB6M"),
    ("MM Bundle Yearly","MMB1Y")
)

class Membership(models.Model):
    slug= models.SlugField()
    m_type= models.CharField(choices=MEMBERSHIP_CHOICES, max_length=30, default="Free")
    m_price= models.IntegerField(default=0)
    stripe_plan_id= models.CharField(max_length=40,default="noplan")
    old_stripe_plan_id= models.CharField(max_length=40,default="nooldplan")

    def __str__(self):
        return self.m_type

    #def product(self):
    #    return self.product_set.all().order_by()

class UserMembership(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    stripe_customer_id = models.CharField(max_length=40)
    membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)
    
    
    def __str__(self):
        return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
    
    user_membership, created = UserMembership.objects.get_or_create(
        user=instance)


    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
        new_customer_id = stripe.Customer.create(email=instance.email)
        free_membership = Membership.objects.filter(m_type='Free').first()

        user_membership.stripe_customer_id = new_customer_id['id']
        user_membership.membership = free_membership
        user_membership.save()


post_save.connect(post_save_usermembership_create,sender=settings.AUTH_USER_MODEL)

class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=40,default="")
    sub_active = models.BooleanField(default=False)

    def __str__(self):
        return self.user_membership.user.username

    @property
    def get_created_date(self):
        sub = stripe.Subscription.retrieve(self.stripe_subscription_id)
        return datetime.fromtimestamp(sub.created)
    @property
    def get_next_billing_date(self):
        sub = stripe.Subscription.retrieve(self.stripe_subscription_id)
        return datetime.fromtimestamp(sub.current_period_end)

class MembershipDiscord(models.Model):
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    discord_private = models.BigIntegerField(max_length=50,default=0)

    def __str__(self):
        return self.membership.m_type

class MembershipTV(models.Model): 
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    tv_inviteonly = models.CharField(max_length=50,default="")

    def __str__(self):
        return self.membership.m_type

class MembershipMT5(models.Model):
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    mt5_ea_name = models.CharField(max_length=50,default="")
    is_mt5 = models.BooleanField(default=False)

    def __str__(self):
        return self.membership.m_type

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from auth_f.models import User


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'tv_acct', 'mt5_acct']

home/views.py
from calendar import month
import time
from django import conf
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from auth_f.views import EmailThread

from .models import Membership, MembershipMT5, UserMembership, Subscription, MembershipDiscord, MembershipTV
from auth_f.models import User
from .forms import UserUpdateForm
from django.contrib import messages
import zipfile
from validate_email import validate_email
from django.conf import settings
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

import requests
from dateutil.relativedelta import relativedelta
from datetime import date
from decouple import config
from django.core import serializers
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from auth_f.utils import generate_token
from django.core.mail import EmailMessage
from django.conf import settings
# region Selenium imports
from selenium import webdriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import FirefoxOptions
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
import os
import re
from selenium.common.exceptions import NoSuchElementException,InvalidArgumentException,StaleElementReferenceException,TimeoutException
from datetime import datetime
from time import sleep
import json
from typing import List


#endregion
import os
from xmlrpc.server import SimpleXMLRPCServer
from xmlrpc.server import SimpleXMLRPCRequestHandler

import socket

#region MT5 Licencing classes
class socketserver:
    def __init__(self, address = '', port = 9090):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.address = address
        self.port = port
        self.sock.bind((self.address, self.port))
        self.cummdata = ''
        
    def recvmsg(self):
        self.sock.listen(1)
        self.conn, self.addr = self.sock.accept()
        print('connected to', self.addr)
        self.cummdata = ''

    def __del__(self):
        self.sock.close()

#endregion



#region funcs

def get_user_membership(request):
    user_membership_qs = UserMembership.objects.filter(user=request.user)
    if user_membership_qs.exists():
        return user_membership_qs.first()
    return None


def get_user_subscription(request):
    user_subscription_qs = Subscription.objects.filter(
        user_membership=get_user_membership(request))
    if user_subscription_qs.exists():
        user_subscription = user_subscription_qs.first()
        return user_subscription
    return None


def get_selected_membership(request):
    membership_type = request.session['selected_membership_type']
    selected_membership_qs = Membership.objects.filter(
        m_type=membership_type)
    if selected_membership_qs.exists():
        return selected_membership_qs.first()
    return None

#endregion


#region APP views
def HomePage(request):
    print(request.method)
    if request.method == 'POST':
        fm=""
        if 'btn_mmbundle' in request.POST:
            ddv_1 = request.POST.get('dd_mmbundle')
            if ddv_1 == "1": fm =  "MM Bundle 1M"
            elif ddv_1 == "2": fm =  "MM Bundle 1M"
            elif ddv_1 == "3": fm =  "MM Bundle 3M"
            elif ddv_1 == "4": fm =  "MM Bundle 6M"
            elif ddv_1 == "5": fm =  "MM Bundle 1Y"
        elif 'btn_mmsuite' in request.POST:
            ddv_2 = request.POST.get('dd_mmsuite')
            if ddv_2 == "1": fm =  "MM Bundle 1M"
            elif ddv_2 == "2": fm =  "MM Bundle 1M"
            elif ddv_2 == "3": fm =  "MM Bundle 3M"
            elif ddv_2 == "4": fm =  "MM Bundle 6M"
            elif ddv_2 == "5": fm =  "MM Bundle 1Y"
        elif 'btn_mmsigma' in request.POST:
            ddv_3 = request.POST.get('dd_mmsigma')
            if ddv_3 == "1": fm =  "MM Bundle 1M"
            elif ddv_3 == "2": fm =  "MM Bundle 1M"
            elif ddv_3 == "3": fm =  "MM Bundle 3M"
            elif ddv_3 == "4": fm =  "MM Bundle 6M"
            elif ddv_3 == "5": fm =  "MM Bundle 1Y"
        
        print(fm)
        request.session['selected_membership_type'] = Membership.objects.get(slug="MMB1M").m_type
        return HttpResponseRedirect(reverse("home:products_checkout"))
        
    return(render( request , "home/home.html"))



@login_required
def ProductsCheckout(request):
    user_membership = get_user_membership(request)
    try:
        selected_membership = get_selected_membership(request)
    except:
        return redirect(reverse("home:home"))
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    print(request.method)
    if request.method == "POST":
        print(request.POST)
        token=""
        i=0
        while i<len(request.POST['stripeToken']):
            token += request.POST['stripeToken'][i]
            i=i+1
        # UPDATE FOR STRIPE API CHANGE 2018-05-21

        '''
        First we need to add the source for the customer
        '''
        customer = stripe.Customer.retrieve(user_membership.stripe_customer_id)
        customer.source = token # 4242424242424242
        customer.save()

        '''
        Now we can create the subscription using only the customer as we don't need to pass their
        credit card source anymore
        '''

        subscription = stripe.Subscription.create(
            customer=user_membership.stripe_customer_id,
            items=[
                { "plan": selected_membership.stripe_plan_id },
            ]
        )
        return redirect(reverse('home:products_transaction',
                                kwargs={
                                    'subscription_id': subscription.id
                                }))


    context = {
        'publishKey': publishKey,
        'selected_membership': selected_membership
    }



    return(render( request , "home/products_checkout.html", context))

@login_required
def ProductsTransaction(request, subscription_id):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)
    user_membership.membership = selected_membership
    user_membership.save()

    sub, created = Subscription.objects.get_or_create(
        user_membership=user_membership)
    sub.stripe_subscription_id = subscription_id
    sub.sub_active = True
    sub.save()

    try:
        del request.session['selected_membership_type']
    except:
        pass
    
    

    messages.info(request, 'Successfully created {} membership'.format(
        selected_membership))
    
    #for n in range(20):
    #    print("setup loop",n)
    #    try:
    #        options = webdriver.ChromeOptions()
    #
    #        options.add_argument(f"user-data-dir=C:\Users\giuli\newMMI\mmi\chrome_d\data{n}")
    #        # options.add_argument("--headless") # Runs Chrome in headless mode.
    #        # options.add_argument('--no-sandbox') # Bypass OS security model
    #        # options.add_argument('--disable-gpu')
    #
    #        driver = webdriver.Chrome(executable_path=os.path.abspath("./chromedriver.exe"),options=options)
    #        driver.implicitly_wait(8)
    #        sleep(3)
    #        driver.get("https://www.tradingview.com/")
    #        print("setup completed")
    #        tv_login(driver=driver)
    #        tv_get_all_charts(driver=driver)
    #        break
    #    except InvalidArgumentException:
    #        print("dir in use... changing dir")
    #        if driver:
    #            driver.quit()
    #            driver = None

    return redirect(reverse('home:home'))


def ProductsPage(request):
    return(render( request , "home/products.html"))


def AboutUsPage(request):
    return(render( request , "home/about_us.html"))

@login_required
def ProfilePage(request):
    user_membership = get_user_membership(request)
    user_subscription = get_user_subscription(request)
    is_mt5 = False
    if MembershipMT5.objects.filter(membership=user_membership.membership).exists():
        is_mt5 = MembershipMT5.objects.filter(membership=user_membership.membership).first().is_mt5
    context = {
        'user_membership': user_membership,
        'user_subscription': user_subscription,
        'user': request.user,
        'is_mt5': is_mt5
    }
    return render(request, "home/profile.html", context)


@login_required
def ProfileMigrateSub(request):
    if(request.method=="POST"):

        _id = request.user.id
        u_id = get_user_membership(request)
        user_membership = get_user_membership(request)
        old_membership_raw = request.POST.get("old_membership")
        print(stripe.api_key)
        print(old_membership_raw)
        um = Membership.objects.filter(m_type=old_membership_raw).first()
        old_membership = Membership.objects.filter(m_type=old_membership_raw).first().old_stripe_plan_id
        new_membership = Membership.objects.filter(m_type=old_membership_raw).first().stripe_plan_id

        context = {'has_error': False, 'data': request.POST}
        stripe_cid = request.POST.get('stripe_cid')
        data = stripe.Subscription.list()
        oldsub = stripe.Subscription.retrieve(
            stripe_cid,
            
        )   
        print(oldsub)
        _cust = oldsub['customer']
        _oldsubid = oldsub['id']
        custsub=""
        is_moresubs = data['data'][0]['items']['has_more']
        
        subs_arr = data['data'][0]['items']['data']
        if _oldsubid == stripe_cid:
            
            oldsub_ends = oldsub["current_period_end"] 
            #trial = (datetime.fromtimestamp(oldsub_ends) - date.today()).days
            #print(trial)

templates/home/profile.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block content %}


<!-- ===============================================-->
<!--    Main Content-->
<!-- ===============================================-->
<main class="main min-vh-100" id="top">


    <!-- ============================================-->
    <!-- Preloader ==================================-->
    <div class="preloader" id="preloader">
        <div class="loader">
        <div class="line-scale-pulse-out-rapid">
            <div> </div>
            <div></div>
            <div></div>
            <div></div>
            <div> </div>
        </div>
        </div>
    </div>
    <!-- ============================================-->
    <!-- End of Preloader ===========================-->


    <!-- ============================================-->
    <!-- <section> begin ============================-->
    <section class="py-0" id="page-profile">

        <div class="container-fluid">
        <div class="row">
            <div class="col-xl-7 px-0">
            <div class="sticky-top overflow-hidden min-vh-50 min-vh-xl-100">
                <div class="bg-holder" style="background-image:url({% static 'img/nbarlogo.jpg' %});" data-zanim-trigger="scroll" data-zanim-lg='{"animation":"zoom-out-slide-right","delay":0.4}'>
                </div>
                <!--/.bg-holder-->

            </div>
            </div>
            <div class="col-xl-5 bg-white py-6">
            <div class="row h-100 flex-center">
                <div class="col-lg-8">
                <div class="row justify-content-center" data-zanim-timeline="{}" data-zanim-trigger="scroll">
                    <div class="col-md-10 col-lg-12">
                    <div class="overflow-hidden">
                        <h4 data-zanim-xs='{"delay":0.1}'>Welcome, {{user.username}}.</h4>
                    </div>
                    <div class="overflow-hidden">
                        <h6 class="text-700 fw-normal text-uppercase ls mb-4" data-zanim-xs='{"delay":0.2}'>MoneyMovesInvestments, member.</h6>
                        <br>
                        <a class="btn btn-primary" href="{% url 'home:profile_update' %}">Edit Details</a>
                        {% if user_membership.membership.m_type == "Free" %}
                            <a class="btn btn-primary" href="{% url 'home:profile_migrate_sub' %}">Migrate Subscription</a>
                        {% endif %}
                        <br>
                        <br>
                        <br>
                        {% if user_membership.membership.m_type != "Free" %}
                            <a class="btn btn-primary" href="{% url 'home:profile_cancel_sub' %}">Cancel Subscription</a>
                            <br>
                            <br>
                            <form method="GET" action="{% url 'home:tv_auth' %}">
                                <a class="btn btn-primary" href="{% url 'home:tv_auth' %}">Enable TV</a>
                                <br>
                            </form>
                            <br>
                            {% if is_mt5 == True %}
                                <form method="GET" action="{% url 'home:mt5_license' %}">
                                    <a class="btn btn-primary" href="{% url 'home:mt5_license' %}">License MT5 Account</a>
                                    <br>
                                </form>
                            {% endif %}
                            <br>
                            <form method="POST" action="{% url 'home:discord_auth' %}">
                                <a class="btn btn-primary" href="{% url 'home:discord_auth' %}">Enable Discord</a>
                            </form>
                        {% endif %}
                        <br>
                        <br>
                        {% if request.user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'home:profile_ad_ctable' %}">Active Customers Table</a>
                        {% endif %}
                        <br>
                        <br>
                        <br>
                        
                    </div>
                    </div>
                    <div class="col-md-7 col-lg-12">
                    <div class="overflow-hidden">
                        
                        <table class="table table-dark">
                            <tbody>
                                <tr>
                                    <th>Membership</th>
                                    <td>{{ user_membership.membership.m_type }}</td>
                                </tr>
                                <tr>
                                    <th>Membership Next Payment</th>
                                    {% if user_subscription != None %}  
                                    <td>{{ user_subscription.get_next_billing_date }}</td>
                                    {% else %}
                                    <td>No Active Membership</td>
                                    {% endif %}
                                </tr>
                                
                                <tr>
                                    <th>Membership Fee</th>
                                    <td>{{user_membership.membership.m_price}}</td>
                                </tr>
                                <tr>

                                    <th>Email Address</th>
                                    <td>{{user.email}}</td>
                                </tr>
                                <tr>
                                    <th>Date Joined</th>
                                    {% if user_subscription != None %} 
                                    <td>{{ user_subscription.get_created_date }}</td>
                                    {% else %}
                                    <td>No Active Membership</td>
                                    {% endif %}
                                </tr>
                                <tr>
                                    <th>MT5 Account #</th>
                                    <td>{{user.mt5_acct}}</td>
                                </tr>
                                <tr>
                                    <th>MT5 Psw</th>
                                    <td>{{user.mt5_bk}}</td>
                                </tr>
                                <tr>
                                    <th>TradingView Account</th>
                                    <td>{{user.tv_acct}}</td>
                                </tr>
                                <tr>
                                    <th>Discord ID</th>
                                    <td>{{user.discord_acct}}</td>
                                </tr>
                                <tr>
                                    <th>Discord Access Token</th>
                                    <td>{{user.discord_at}}</td>
                                </tr>
                            </tbody>
                        </table>



                        
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
        <!-- end of .container-->

    </section>
    <!-- <section> close ============================-->
    <!-- ============================================-->


</main>
<!-- ===============================================-->
<!--    End of Main Content-->
<!-- ===============================================-->







{% endblock content %}

templates/home/profile_ad_ctable.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block content %}


<!-- ===============================================-->
<!--    Main Content-->
<!-- ===============================================-->
<main class="main min-vh-100" id="top">


    <!-- ============================================-->
    <!-- Preloader ==================================-->
    <div class="preloader" id="preloader">
        <div class="loader">
        <div class="line-scale-pulse-out-rapid">
            <div> </div>
            <div></div>
            <div></div>
            <div></div>
            <div> </div>
        </div>
        </div>
    </div>
    <!-- ============================================-->
    <!-- End of Preloader ===========================-->


    <!-- ============================================-->
    <!-- <section> begin ============================-->
    <section class="py-0" id="page-profile">

        <div class="container-fluid">
        <div class="row">
            <div class="col-xl-7 px-0">
            <div class="sticky-top overflow-hidden min-vh-50 min-vh-xl-100">
                <div class="bg-holder" style="background-image:url({% static 'img/nbarlogo.jpg' %});" data-zanim-trigger="scroll" data-zanim-lg='{"animation":"zoom-out-slide-right","delay":0.4}'>
                </div>
                <!--/.bg-holder-->

            </div>
            </div>
            <div class="col-xl-5 bg-white py-6">
            <div class="row h-100 flex-center">
                <div class="col-lg-8">
                <div class="row justify-content-center" data-zanim-timeline="{}" data-zanim-trigger="scroll">
                    <div class="col-md-10 col-lg-12">
                    <div class="overflow-hidden">
                        <h4 data-zanim-xs='{"delay":0.1}'>Welcome, {{user.username}}.</h4>
                    </div>
                    <div class="overflow-hidden">
                        <h6 class="text-700 fw-normal text-uppercase ls mb-4" data-zanim-xs='{"delay":0.2}'>MoneyMovesInvestments, member.</h6>
                        
                        
                    </div>
                    </div>
                    <div class="col-md-7 col-lg-12">
                    <div class="overflow-hidden">
                        <form class="mt-5" method="POST" action= {% url 'home:profile_update' %}>
                            {% csrf_token %}
                            <table class="table table-dark">
                                <tbody>
                                    <tr>
                                        <th>Username</th>
                                        <th>Email</th>
                                        <th>Act.Sub Since</th>
                                        <th>TV Account</th>
                                        <th>MT5 Account</th>
                                        <th>Del</th>
                                        <th>Upt</th>
                                      </tr>
                                    {% for cust in all_cust}
                                    <tr>
                                        
                                        <td>{{all_cust.username}}</td>
                                        <td>{{all_cust.email}}</td>
                                        <td>{{all_cust.date_joined}}</td>
                                        <td>{{all_cust.date_expires}}</td>
                                        <td>{{all_cust.tv_acct}}</td>
                                        <td>{{all_cust.mt5_acct}}</td>
                                        <td><a class="btn btn-primary" href="#">X</a></td>
                                        <td><a class="btn btn-primary" href="#">...</a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            <br>
                            <br>
                            <br>
                            <input class="btn btn-primary" type="button" href="{% url 'home:profile' %}" value="Profile">
                            <br>
                            

                        </form>


                        
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
        <!-- end of .container-->

    </section>
    <!-- <section> close ============================-->
    <!-- ============================================-->


</main>
<!-- ===============================================-->
<!--    End of Main Content-->
<!-- ===============================================-->






{% endblock content %}

templates/home/profile_cancelsub.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block content %}


<!-- ===============================================-->
<!--    Main Content-->
<!-- ===============================================-->
<main class="main min-vh-100" id="top">


    <!-- ============================================-->
    <!-- Preloader ==================================-->
    <div class="preloader" id="preloader">
        <div class="loader">
        <div class="line-scale-pulse-out-rapid">
            <div> </div>
            <div></div>
            <div></div>
            <div></div>
            <div> </div>
        </div>
        </div>
    </div>
    <!-- ============================================-->
    <!-- End of Preloader ===========================-->


    <!-- ============================================-->
    <!-- <section> begin ============================-->
    <section class="py-0" id="page-profile">

        <div class="container-fluid">
        <div class="row">
            <div class="col-xl-7 px-0">
            <div class="sticky-top overflow-hidden min-vh-50 min-vh-xl-100">
                <div class="bg-holder" style="background-image:url({% static 'img/nbarlogo.jpg' %});" data-zanim-trigger="scroll" data-zanim-lg='{"animation":"zoom-out-slide-right","delay":0.4}'>
                </div>
                <!--/.bg-holder-->

            </div>
            </div>
            <div class="col-xl-5 bg-white py-6">
            <div class="row h-100 flex-center">
                <div class="col-lg-8">
                <div class="row justify-content-center" data-zanim-timeline="{}" data-zanim-trigger="scroll">
                    <div class="col-md-10 col-lg-12">
                    <div class="overflow-hidden">
                        <h4 data-zanim-xs='{"delay":0.1}'>Welcome, {{user.username}}.</h4>
                    </div>
                    <div class="overflow-hidden">
                        <h6 class="text-700 fw-normal text-uppercase ls mb-4" data-zanim-xs='{"delay":0.2}'>MoneyMovesInvestments, member.</h6>
                        <br>
                        <br>
                        <h6>Are you sure you want to cancel?</h6>
                        
                    </div>
                    </div>
                    <div class="col-md-7 col-lg-12">
                    <div class="overflow-hidden">
                        <form class="mt-5" method="POST" action= {% url 'home:profile_cancel_sub' %}>
                            {% csrf_token %}
                            

                            <br>
                            <br>
                            <br>
                            <input class="btn btn-primary" type="submit" value="Yes">
                            <br>
                            

                        </form>
                        <br>
                        <input class="btn btn-primary" href="{% url 'home:profile' %}" value="No">
                        <br>

                        
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
        <!-- end of .container-->

    </section>
    <!-- <section> close ============================-->
    <!-- ============================================-->


</main>
<!-- ===============================================-->
<!--    End of Main Content-->
<!-- ===============================================-->






{% endblock content %}