auth_f/urls.py
from django.urls import path,include


#from .views import HomePage
from . import views

app_name = "auth_f"

urlpatterns = [

    path('login', views.LoginPage, name="login"),
    path('register', views.RegisterPage, name="register"),
    path("logout", views.Logout, name='logout'),
    path('activate_user/<uidb64>/<token>',
         views.ActivateUser, name='activate'),
] 

home/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

#from .views import HomePage
from . import views

app_name = "home"

urlpatterns = [

    path('', views.HomePage, name="home"),
    #path('products', views.ProductsPage, name="products"),
    path('products_checkout', views.ProductsCheckout, name="products_checkout"),
    path('products_transaction/<subscription_id>', views.ProductsTransaction, name="products_transaction"),
    path('about', views.AboutUsPage, name="about"),
    path('profile', views.ProfilePage, name="profile"),
    path('profile/update', views.ProfileUpdate, name="profile_update"),
    path('profile/migrate_sub', views.ProfileMigrateSub, name="profile_migrate_sub"),
    path('profile/cancel_sub', views.ProfileCancelSub, name="profile_cancel_sub"),
    
    path('profile/discord_auth', views.DiscordAuth, name="discord_auth"),
    path('profile/tv_auth', views.TvAuth, name="tv_auth"),
    path('profile/mt5_license', views.MT5Licence, name="mt5_license"),
    path('profile/discord_authc', views.DiscordAuthC, name="discord_authc"),
    path('profile/get_ctable', views.AdCustomerTable, name="profile_ad_ctable"),
    path('algo_getting_started', views.AlgoGSPage, name="algo_gs"),
    path('algo_mmsigma', views.AlgoMMSIGMAPage, name="algo_mmsigma"),
    
    path('auth_f/', include('auth_f.urls')),
    
    

] 

mmi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('auth_f/', include('auth_f.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth_f/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_email_verified = models.BooleanField(default=False)
    tv_acct = models.CharField(max_length=30, default="none")
    mt5_acct = models.CharField(max_length=30, default="none")
    mt5_bk = models.CharField(max_length=50, default="none")
    discord_acct = models.BigIntegerField (default=0 )
    discord_at = models.CharField(max_length=50, default="none")
    tv_ok = models.BooleanField(default=False)
    mt5_ok = models.BooleanField(default=False)

    def __str__(self):
        return self.email

home/models.py
import django
from django.db import models

# Create your models here.

from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

from datetime import date, datetime
import time

from django.utils import timezone

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
    ("Free", "Free"),
    ("MM Bundle Monthly","MMB1M"),
    ("MM Bundle Quarterly","MMB3M"),
    ("MM Bundle Semestral","MMB6M"),
    ("MM Bundle Yearly","MMB1Y")
)

class Membership(models.Model):
    slug= models.SlugField()
    m_type= models.CharField(choices=MEMBERSHIP_CHOICES, max_length=30, default="Free")
    m_price= models.IntegerField(default=0)
    stripe_plan_id= models.CharField(max_length=40,default="noplan")
    old_stripe_plan_id= models.CharField(max_length=40,default="nooldplan")

    def __str__(self):
        return self.m_type

    #def product(self):
    #    return self.product_set.all().order_by()

class UserMembership(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    stripe_customer_id = models.CharField(max_length=40)
    membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)
    
    
    def __str__(self):
        return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
    
    user_membership, created = UserMembership.objects.get_or_create(
        user=instance)


    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
        new_customer_id = stripe.Customer.create(email=instance.email)
        free_membership = Membership.objects.filter(m_type='Free').first()

        user_membership.stripe_customer_id = new_customer_id['id']
        user_membership.membership = free_membership
        user_membership.save()


post_save.connect(post_save_usermembership_create,sender=settings.AUTH_USER_MODEL)

class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=40,default="")
    sub_active = models.BooleanField(default=False)

    def __str__(self):
        return self.user_membership.user.username

    @property
    def get_created_date(self):
        sub = stripe.Subscription.retrieve(self.stripe_subscription_id)
        return datetime.fromtimestamp(sub.created)
    @property
    def get_next_billing_date(self):
        sub = stripe.Subscription.retrieve(self.stripe_subscription_id)
        return datetime.fromtimestamp(sub.current_period_end)

class MembershipDiscord(models.Model):
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    discord_private = models.BigIntegerField(max_length=50,default=0)

    def __str__(self):
        return self.membership.m_type

class MembershipTV(models.Model): 
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    tv_inviteonly = models.CharField(max_length=50,default="")

    def __str__(self):
        return self.membership.m_type

class MembershipMT5(models.Model):
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    mt5_ea_name = models.CharField(max_length=50,default="")
    is_mt5 = models.BooleanField(default=False)

    def __str__(self):
        return self.membership.m_type

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from auth_f.models import User


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'tv_acct', 'mt5_acct']

auth_f/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from validate_email import validate_email
from .models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from helpers.decorators import auth_user_should_not_access
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from .utils import generate_token
from django.core.mail import EmailMessage
from django.conf import settings
import threading
from os import environ
import smtplib
import email.utils
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


#region Email Functions

class EmailThread(threading.Thread):

    def __init__(self, email):
        self.email = email
        threading.Thread.__init__(self)

    def run(self):
        self.email.send()


def send_activation_email(user, request):
    current_site = get_current_site(request)
    email_subject = 'Activate your account'
    email_body = render_to_string('home/auth_f/activate.html', {
        'user': user,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': generate_token.make_token(user)
    })

    email = EmailMessage(subject=email_subject, body=email_body,
                         from_email=settings.EMAIL_FROM_USER,
                         to=[user.email]
                         )

    if not settings.TESTING:
        EmailThread(email).start()

#endregion

#region APP views
@auth_user_should_not_access
def LoginPage(request):
    if request.method == 'POST':
        context = {'data': request.POST}
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        print(username)
        print(password)
        print(user)

        if user and not user.is_email_verified:
            messages.add_message(request, messages.ERROR,
                                    'Email is not verified, please check your email inbox')
            return render(request, 'home/auth_f/login.html', context, status=401)

        if not user:
            messages.add_message(request, messages.ERROR,
                                    'Invalid credentials, try again')
            return render(request, 'home/auth_f/login.html', context, status=401)

        login(request, user)

        messages.add_message(request, messages.SUCCESS,
                                f'Welcome {user.username}')

        return redirect(reverse('home:home'))

    return render(request, 'home/auth_f/login.html')

@auth_user_should_not_access
def RegisterPage(request):
    if request.method == "POST":
        context = {'has_error': False, 'data': request.POST}
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        tv_acct = request.POST.get('tv_acct')
        mt5_acct = request.POST.get('mt5_acct')

        if len(password) < 6:
            messages.add_message(request, messages.ERROR,
                                 'Password should be at least 6 characters')
            context['has_error'] = True

        if password != password2:
            messages.add_message(request, messages.ERROR,
                                 'Password mismatch')
            context['has_error'] = True

        if not validate_email(email):
            messages.add_message(request, messages.ERROR,
                                 'Enter a valid email address')
            context['has_error'] = True

        if not username:
            messages.add_message(request, messages.ERROR,
                                 'Username is required')
            context['has_error'] = True

        if User.objects.filter(username=username).exists():
            messages.add_message(request, messages.ERROR,
                                 'Username is taken, choose another one')
            context['has_error'] = True

            return render(request, 'home/auth_f/register.html', context, status=409)

        if User.objects.filter(email=email).exists():
            messages.add_message(request, messages.ERROR,
                                 'Email is taken, choose another one')
            context['has_error'] = True

            return render(request, 'home/auth_f/register.html', context, status=409)

        if context['has_error']:
            return render(request, 'home/auth_f/register.html', context)

        user = User.objects.create_user(username=username, email=email, tv_acct=tv_acct, mt5_acct = mt5_acct)
        user.set_password(password)
        user.save()

        

        if not context['has_error']:

            send_activation_email(user, request)

            messages.add_message(request, messages.SUCCESS,
                                 'We sent you an email to verify your account')
            return redirect('auth_f:login')

    return render(request, 'home/auth_f/register.html')


def Logout(request):
    logout(request)
    return redirect('/')


def ActivateUser(request, uidb64, token):

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))

        user = User.objects.get(pk=uid)

    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        user.is_email_verified = True
        user.save()

        messages.add_message(request, messages.SUCCESS,
                             'Email verified, you can now login')
        return redirect(reverse('auth_f:login'))

    return render(request, 'home/auth_f/activate-failed.html', {"user": user})

#endregion

templates/home/auth_f/activate-failed.html
<p>Someone went wrong with your link</p>

templates/home/auth_f/activate.html
{% autoescape off %}


Hi {{user.username}}

Please use the link below to verify your account.


http://{{domain}}{% url 'auth_f:activate' uidb64=uid token=token %}


{% endautoescape %}

templates/home/auth_f/cancel.html
{% autoescape off %}


Hi {{user.username}}

You correctly unsubscribed. We hope to see you back soon.

{% endautoescape %}

templates/home/auth_f/login.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block content %}





<!-- ===============================================-->
<!--    Main Content-->
<!-- ===============================================-->
<main class="main min-vh-100" id="top">


    <!-- ============================================-->
    <!-- Preloader ==================================-->
    <div class="preloader" id="preloader">
        <div class="loader">
        <div class="line-scale-pulse-out-rapid">
            <div> </div>
            <div></div>
            <div></div>
            <div></div>
            <div> </div>
        </div>
        </div>
    </div>
    <!-- ============================================-->
    <!-- End of Preloader ===========================-->


    <!-- ============================================-->
    <!-- <section> begin ============================-->
    <section class="py-0">

        <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 px-0">
            <div class="sticky-top vh-lg-100 py-9">
                <div class="bg-holder" style="background-image:url({% static 'img/auth_bg.png' %});" data-zanim-trigger="scroll" data-zanim-lg='{"animation":"zoom-out-slide-right","delay":0.4}'>
                </div>
                <!--/.bg-holder-->

            </div>
            </div>
            <div class="col-lg-6 py-6">
            <div class="row h-100 align-items-center justify-content-center">
                <div class="col-sm-8 col-md-6 col-lg-10 col-xl-8" data-zanim-xs='{"delay":0.5,"animation":"slide-right"}' data-zanim-trigger="scroll">
                <h3 class="display-4 fs-2">Perfect for Beginners,<br />and Experienced traders.</h3>
                <h6 class="text-danger mt-3">Specially created from who does Algo Trading for who does Algo Trading.</h6>
                <form class="mt-5" method="POST" action={% url 'auth_f:login' %}>
                    {% csrf_token %}
                    <div class="mb-3">
                    <input class="form-control bg-light" type="text" required name="username" placeholder="Username" value="{{ data.username }}"/>
                    </div>
                    <div class="mb-0">
                    <input class="form-control bg-light" type="password" required name="password" placeholder="Password" />
                    </div>

                    <div class="mb-0 form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        Log As Admin
                    </label>
                    </div>


                    <div class="mb-3 d-grid">
                    <button class="btn btn-dark mt-3" type="submit" name="submit">Sign In</button>
                    </div>
                    <div class="mb-3 w-100 position-relative text-center mt-4">
                    <hr class="text-300" />
                    <div class="absolute-centered px-3 font-sans-serif fs--1 text-500">or Sign-In with</div>
                    </div>
                    <div class="mb-0">
                    <div class="row gx-2">
                        <div class="col-6 d-grid"><a class="btn btn-outline-danger btn-sm mt-2" href="#!"><span class="fab fa-google-plus-g me-2" data-fa-transform="grow-8"></span> google</a></div>
                        <div class="col-6 d-grid"><a class="btn btn-outline-primary btn-sm mt-2" href="#!"><span class="fab fa-facebook me-2" data-fa-transform="grow-8"></span> facebook</a></div>
                    </div>
                    </div>
                    
                </form>
                </div>
            </div>
            </div>
        </div>
        </div>
        <!-- end of .container-->

    </section>
    <!-- <section> close ============================-->
    <!-- ============================================-->


</main>
<!-- ===============================================-->
<!--    End of Main Content-->
<!-- ===============================================-->


  




{% endblock content %}

templates/home/auth_f/register.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block content %}


<!-- ===============================================-->
<!--    Main Content-->
<!-- ===============================================-->
<main class="main min-vh-100" id="top">


    <!-- ============================================-->
    <!-- Preloader ==================================-->
    <div class="preloader" id="preloader">
        <div class="loader">
        <div class="line-scale-pulse-out-rapid">
            <div> </div>
            <div></div>
            <div></div>
            <div></div>
            <div> </div>
        </div>
        </div>
    </div>
    <!-- ============================================-->
    <!-- End of Preloader ===========================-->


    <!-- ============================================-->
    <!-- <section> begin ============================-->
    <section class="py-0">

        <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 px-0">
            <div class="sticky-top vh-lg-100 py-9">
                <div class="bg-holder" style="background-image:url({% static 'img/auth_bg.png' %});" data-zanim-trigger="scroll" data-zanim-lg='{"animation":"zoom-out-slide-right","delay":0.4}'>
                </div>
                <!--/.bg-holder-->

            </div>
            </div>
            <div class="col-lg-6 py-6">
            <div class="row h-100 align-items-center justify-content-center">
                <div class="col-sm-8 col-md-6 col-lg-10 col-xl-8" data-zanim-xs='{"delay":0.5,"animation":"slide-right"}' data-zanim-trigger="scroll">
                <h3 class="display-4 fs-2">Perfect for Beginners,<br />and Experienced traders.</h3>
                <h6 class="text-danger mt-3">Specially created from who does Algo Trading for who does Algo Trading.</h6>
                <form class="mt-5" method="POST" {% url 'auth_f:register' %}>
                    {% csrf_token %}
                    <div class="row gy-4 align-items-center mb-4">
                    <div class="col-12">
                        <input class="form-control bg-light" placeholder="Username" type="text" name="username" value="{{data.username}}" />
                    </div>
                    <div class="col-12">
                        <input class="form-control bg-light" placeholder="Email Address" type="text" name="email" value="{{data.email}}" />
                    </div>
                    <div class="col-6">
                        <input class="form-control bg-light" type="password" name="password" placeholder="Password" />
                    </div>
                    <div class="col-6">
                        <input class="form-control bg-light" type="password" name="password2" placeholder="Confirm Password" />
                    </div>
                    <div class="col-6">
                        <input class="form-control bg-light" type="text" placeholder="TV Account" name = "tv_acct" value="{{data.tv_acct}}" />
                    </div>
                    <div class="col-6">
                        <input class="form-control bg-light" type="text" placeholder="MT5 Account" name = "mt5_acct" value="{{data.mt5_acct}}" />
                    </div>
                    
                    <div class="row mb-4 align-items-center">
                        <div class="col-auto d-grid">
                            <input class="btn btn-dark" type="submit" name="submit" value="Create an Account" />
                        </div>
                        <div class="col-sm">
                            <p class="fs--1 text-700 mb-0 font-sans-serif mt-2 mt-lg-0">By signing up, you agree to the <a class="text-black" href="#!">terms and conditions.</a></p>
                        </div>
                        </div>

                    </div>
                    
                    </div>
                    
                </form>
                </div>
            </div>
            </div>
        </div>
        </div>
        <!-- end of .container-->

    </section>
    <!-- <section> close ============================-->
    <!-- ============================================-->


</main>
<!-- ===============================================-->
<!--    End of Main Content-->
<!-- ===============================================-->




{% endblock content %}